using System.Globalization;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using Tsukimichi.Core.Model;

namespace Tsukimichi.Core.Links;

/// <summary>A quest's ids on two sites: its Lodestone Eorzea Database hash and its Console Games Wiki page title; empty when unknown.</summary>
public readonly record struct ExternalQuestIds(string LodestoneId, string WikiTitle);

/// <summary>
/// <c>Tsukimichi/Data/external_ids.json</c> (1.8.0, "Open on…"): the link table the "Open on…" menus, Copy for Discord,
/// Copy table as TSV and the export's <c>lodestoneId</c> read. Generated offline by <c>Tsukimichi.Verify links</c> from
/// <c>docs/data/quest-verification.csv</c> (each quest's Lodestone page hash and the wiki page its facts were checked
/// against) and <c>docs/data/reward-verification.csv</c> (the FFXIV Collect id of each Moonlit reward the tool matched).
/// The plugin never fetches anything (feature plan v5, decision 8): a quest the table lacks falls back to the sites'
/// own search (<see cref="ExternalLinks"/>). Immutable.
/// <code>
/// { "quests": { "65537": ["a7cbeb1c618", "A Good Adventurer Is Hard to Find"] }, "collect": { "Mount": { "15": 23 } } }
/// </code>
/// </summary>
public sealed class ExternalIds
{
    public const string FileName = "external_ids.json";

    private const string SchemaNote =
        "Quest sheet row id -> [Lodestone Eorzea Database hash, Console Games Wiki page title] (\"\" when unknown), and reward kind -> reward id -> FFXIV Collect id. " +
        "Generated by `Tsukimichi.Verify links` from docs/data/quest-verification.csv and docs/data/reward-verification.csv (facts only: ids and titles). " +
        "The plugin only builds browser links from it and never fetches anything. Do not edit by hand: rerun the command.";

    private readonly Dictionary<uint, ExternalQuestIds> quests;
    private readonly Dictionary<(RewardKind Kind, uint RewardId), uint> collect;

    public ExternalIds(IReadOnlyDictionary<uint, ExternalQuestIds> quests, IReadOnlyDictionary<(RewardKind Kind, uint RewardId), uint> collect, IReadOnlyList<string>? warnings = null)
    {
        ArgumentNullException.ThrowIfNull(quests);
        ArgumentNullException.ThrowIfNull(collect);
        this.quests = new Dictionary<uint, ExternalQuestIds>(quests);
        this.collect = new Dictionary<(RewardKind, uint), uint>(collect);
        Warnings = warnings ?? [];
    }

    /// <summary>No table: every link falls back to a search.</summary>
    public static ExternalIds Empty { get; } = new(new Dictionary<uint, ExternalQuestIds>(), new Dictionary<(RewardKind, uint), uint>());

    /// <summary>Every quest the table names, by Quest sheet row id.</summary>
    public IReadOnlyDictionary<uint, ExternalQuestIds> Quests => quests;

    /// <summary>FFXIV Collect ids by reward kind and reward id.</summary>
    public IReadOnlyDictionary<(RewardKind Kind, uint RewardId), uint> Collect => collect;

    /// <summary>Problems met while reading; the entries that parsed are kept.</summary>
    public IReadOnlyList<string> Warnings { get; }

    /// <summary>The quest's Lodestone database hash ("a7cbeb1c618"); null when the table has none.</summary>
    public string? LodestoneId(uint rowId) => quests.TryGetValue(rowId, out var ids) && ids.LodestoneId.Length > 0 ? ids.LodestoneId : null;

    /// <summary>The quest's Console Games Wiki page title ("A Bone to Pick (Quest)"); null when the table has none.</summary>
    public string? WikiTitle(uint rowId) => quests.TryGetValue(rowId, out var ids) && ids.WikiTitle.Length > 0 ? ids.WikiTitle : null;

    /// <summary>The reward's FFXIV Collect id; null when the table has none.</summary>
    public uint? CollectId(RewardKind kind, uint rewardId) => collect.TryGetValue((kind, rewardId), out var id) ? id : null;

    /// <summary>Reads the file; a missing or unreadable file is <see cref="Empty"/> with a warning.</summary>
    public static ExternalIds Load(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        if (!File.Exists(path))
        {
            return new ExternalIds(new Dictionary<uint, ExternalQuestIds>(), new Dictionary<(RewardKind, uint), uint>(), [$"{Path.GetFileName(path)} not found; \"Open on…\" falls back to each site's search."]);
        }

        try
        {
            return Parse(File.ReadAllText(path), Path.GetFileName(path));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return new ExternalIds(new Dictionary<uint, ExternalQuestIds>(), new Dictionary<(RewardKind, uint), uint>(), [$"{Path.GetFileName(path)} could not be read: {ex.Message}"]);
        }
    }

    /// <summary>Parses the file's text; entries that do not parse are skipped with a warning.</summary>
    public static ExternalIds Parse(string json, string fileName = FileName)
    {
        ArgumentNullException.ThrowIfNull(json);
        var warnings = new List<string>();
        JsonNode? root;
        try
        {
            root = JsonNode.Parse(json, documentOptions: new JsonDocumentOptions { CommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true });
        }
        catch (JsonException ex)
        {
            return new ExternalIds(new Dictionary<uint, ExternalQuestIds>(), new Dictionary<(RewardKind, uint), uint>(), [$"{fileName} could not be parsed: {ex.Message}"]);
        }

        var quests = new Dictionary<uint, ExternalQuestIds>();
        var collect = new Dictionary<(RewardKind, uint), uint>();
        if (root is not JsonObject obj)
        {
            return new ExternalIds(quests, collect, [$"{fileName}: root is not an object; file ignored."]);
        }

        foreach (var (key, value) in obj["quests"] as JsonObject ?? [])
        {
            if (!uint.TryParse(key, NumberStyles.None, CultureInfo.InvariantCulture, out var rowId)
                || value is not JsonArray { Count: 2 } pair
                || pair[0] is not JsonValue lodestone || !lodestone.TryGetValue<string>(out var hash)
                || pair[1] is not JsonValue wiki || !wiki.TryGetValue<string>(out var title))
            {
                warnings.Add($"{fileName}: quests[\"{key}\"] skipped: expected a row id and [\"hash\", \"title\"]");
                continue;
            }

            quests[rowId] = new ExternalQuestIds(IsLodestoneHash(hash) ? hash : string.Empty, title.Trim());
        }

        foreach (var (kindName, ids) in obj["collect"] as JsonObject ?? [])
        {
            if (!Enum.TryParse<RewardKind>(kindName, ignoreCase: false, out var kind) || !Enum.IsDefined(kind) || ids is not JsonObject map)
            {
                warnings.Add($"{fileName}: collect[\"{kindName}\"] skipped: not a reward kind");
                continue;
            }

            foreach (var (key, value) in map)
            {
                if (!uint.TryParse(key, NumberStyles.None, CultureInfo.InvariantCulture, out var rewardId)
                    || value is not JsonValue v || !v.TryGetValue<uint>(out var collectId) || collectId == 0)
                {
                    warnings.Add($"{fileName}: collect[\"{kindName}\"][\"{key}\"] skipped: expected a reward id and a positive number");
                    continue;
                }

                collect[(kind, rewardId)] = collectId;
            }
        }

        return new ExternalIds(quests, collect, warnings);
    }

    /// <summary>
    /// The file's text: quests by ascending row id, reward kinds by name and ids ascending, so a regeneration diffs
    /// cleanly.
    /// </summary>
    public static string Serialize(IReadOnlyDictionary<uint, ExternalQuestIds> quests, IReadOnlyDictionary<(RewardKind Kind, uint RewardId), uint> collect)
    {
        ArgumentNullException.ThrowIfNull(quests);
        ArgumentNullException.ThrowIfNull(collect);

        // One line per quest and per reward kind keeps the file small and its diffs readable.
        var sb = new StringBuilder();
        sb.Append("{\n  \"_schema\": ").Append(Quote(SchemaNote)).Append(",\n  \"quests\": {");
        var first = true;
        foreach (var (rowId, ids) in quests.OrderBy(static q => q.Key))
        {
            sb.Append(first ? "\n" : ",\n").Append("    \"").Append(rowId.ToString(CultureInfo.InvariantCulture)).Append("\": [")
                .Append(Quote(ids.LodestoneId)).Append(", ").Append(Quote(ids.WikiTitle)).Append(']');
            first = false;
        }

        sb.Append(first ? "},\n" : "\n  },\n").Append("  \"collect\": {");
        first = true;
        foreach (var group in collect.GroupBy(static c => c.Key.Kind).OrderBy(static g => g.Key.ToString(), StringComparer.Ordinal))
        {
            sb.Append(first ? "\n" : ",\n").Append("    ").Append(Quote(group.Key.ToString())).Append(": { ");
            var firstId = true;
            foreach (var (key, id) in group.OrderBy(static c => c.Key.RewardId))
            {
                sb.Append(firstId ? string.Empty : ", ").Append('"').Append(key.RewardId.ToString(CultureInfo.InvariantCulture)).Append("\": ")
                    .Append(id.ToString(CultureInfo.InvariantCulture));
                firstId = false;
            }

            sb.Append(" }");
            first = false;
        }

        sb.Append(first ? "}\n}\n" : "\n  }\n}\n");
        return sb.ToString();
    }

    private static readonly JsonSerializerOptions QuoteOptions = new() { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    private static string Quote(string value) => JsonSerializer.Serialize(value ?? string.Empty, QuoteOptions);

    /// <summary>A Lodestone database hash: lower-case hexadecimal, as the site's URLs carry it.</summary>
    public static bool IsLodestoneHash(string? value)
    {
        if (string.IsNullOrEmpty(value) || value.Length > 32)
        {
            return false;
        }

        foreach (var c in value)
        {
            if (c is not (>= '0' and <= '9') and not (>= 'a' and <= 'f'))
            {
                return false;
            }
        }

        return true;
    }
}
