using System.Text;
using Tsukimichi.Verify.Verify;

namespace Tsukimichi.Verify.Output;

/// <summary>Run parameters stamped into verification-full.md.</summary>
internal sealed record RunInfo(
    string Command,
    string GameVersion,
    string Date,
    string UserAgent,
    double RateSeconds,
    bool Offline,
    int Limit,
    int LiveRequests,
    int CacheHits,
    string Elapsed,
    IReadOnlyCollection<string> BlockedHosts,
    IReadOnlyList<string> Notes);

/// <summary>
/// docs/data/verification-full.md: totals per verdict and per source, every catalogWrong and unresolved row with its
/// evidence, the run parameters. Regenerated from the CSVs so it never disagrees with them. Facts only: ids, levels,
/// names, counts and URLs; no quest or description text.
/// </summary>
internal static class FullReport
{
    public static void Write(string path, IReadOnlyList<QuestRow> quests, IReadOnlyList<RewardRow> rewards, Allowlist allowlist, Version? current, RunInfo run, int catalogQuestCount, IReadOnlyList<(uint RowId, string Name, uint SystemReward, bool Covered)> systemRewardCoverage)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Full-catalog verification (T2a)");
        sb.AppendLine();
        sb.AppendLine($"Generated by `Tsukimichi.Verify {run.Command}` on {run.Date} against game version `{run.GameVersion}`. Facts only (ids, levels, names, counts, URLs); no quest or description text is committed. The long-form rows are in `quest-verification.csv`, one row per quest in `quest-verification-summary.csv`, the unique-reward checks in `reward-verification.csv`; `verification-allowlist.json` excuses known rows until the release named in `until`.");
        sb.AppendLine();
        sb.AppendLine("## Run parameters");
        sb.AppendLine();
        sb.AppendLine("| Parameter | Value |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Game version | `{run.GameVersion}` |");
        sb.AppendLine($"| Date | {run.Date} |");
        sb.AppendLine($"| User-Agent | `{run.UserAgent}` |");
        sb.AppendLine($"| Rate | one request every {run.RateSeconds:F1} s per host, serial |");
        sb.AppendLine($"| Mode | {(run.Offline ? "offline (cache only)" : "online")}{(run.Limit > 0 ? $", --limit {run.Limit}" : string.Empty)} |");
        sb.AppendLine($"| Requests | {run.LiveRequests} live, {run.CacheHits} from cache |");
        sb.AppendLine($"| Wall clock | {run.Elapsed} |");
        sb.AppendLine($"| Hosts that blocked | {(run.BlockedHosts.Count == 0 ? "none" : string.Join(", ", run.BlockedHosts))} |");
        sb.AppendLine($"| Catalog | {catalogQuestCount} named quests; {quests.Select(r => r.RowId).Distinct().Count()} with at least one row |");
        foreach (var note in run.Notes)
        {
            sb.AppendLine($"| Note | {note} |");
        }

        sb.AppendLine();
        sb.AppendLine("## Quest facts: totals per verdict");
        sb.AppendLine();
        Totals(sb, quests.Select(r => (r.Source, r.Verdict)).ToList());

        sb.AppendLine("### Per fact");
        sb.AppendLine();
        var facts = quests.Select(r => r.Fact).Distinct().OrderBy(f => f, StringComparer.Ordinal).ToList();
        var verdictOrder = Enum.GetValues<Verdict>();
        sb.AppendLine("| Fact | " + string.Join(" | ", verdictOrder.Select(Verdicts.Name)) + " |");
        sb.AppendLine("|---|" + string.Concat(verdictOrder.Select(_ => "---:|")));
        foreach (var fact in facts)
        {
            var of = quests.Where(r => r.Fact == fact).ToList();
            sb.AppendLine($"| {fact} | " + string.Join(" | ", verdictOrder.Select(v => of.Count(r => r.Verdict == v))) + " |");
        }

        sb.AppendLine();
        sb.AppendLine("### Per quest (summary file)");
        sb.AppendLine();
        var perQuest = quests.GroupBy(r => r.RowId).Select(g => g.Max(r => Verdicts.Severity(r.Verdict))).ToList();
        foreach (var v in verdictOrder.OrderByDescending(Verdicts.Severity))
        {
            sb.AppendLine($"- {Verdicts.Name(v)} as worst fact: {perQuest.Count(s => s == Verdicts.Severity(v))}");
        }

        sb.AppendLine();
        sb.AppendLine("## Unique rewards: totals per verdict");
        sb.AppendLine();
        Totals(sb, rewards.Select(r => (r.Source, r.Verdict)).ToList());
        sb.AppendLine("### Per kind");
        sb.AppendLine();
        sb.AppendLine("| Kind | " + string.Join(" | ", verdictOrder.Select(Verdicts.Name)) + " |");
        sb.AppendLine("|---|" + string.Concat(verdictOrder.Select(_ => "---:|")));
        foreach (var kind in rewards.Select(r => r.Kind).Distinct().OrderBy(k => k, StringComparer.Ordinal))
        {
            var of = rewards.Where(r => r.Kind == kind).ToList();
            sb.AppendLine($"| {kind} | " + string.Join(" | ", verdictOrder.Select(v => of.Count(r => r.Verdict == v))) + " |");
        }

        sb.AppendLine();
        sb.AppendLine("## Gate");
        sb.AppendLine();
        var questFailures = quests.Where(r => Verdicts.FailsGate(r.Verdict)).ToList();
        var rewardFailures = rewards.Where(r => Verdicts.FailsGate(r.Verdict)).ToList();
        var questOpen = questFailures.Where(r => allowlist.Covering(r, current) is null).ToList();
        var rewardOpen = rewardFailures.Where(r => allowlist.Covering(r, current) is null).ToList();
        sb.AppendLine($"- Quest rows failing the gate: {questFailures.Count} ({questOpen.Count} outside the allowlist)");
        sb.AppendLine($"- Reward rows failing the gate: {rewardFailures.Count} ({rewardOpen.Count} outside the allowlist)");
        sb.AppendLine($"- Allowlist entries: {allowlist.Entries.Count} ({allowlist.Entries.Count(e => Allowlist.Expired(e, current))} expired)");
        sb.AppendLine($"- `summary` exit code: {(questOpen.Count + rewardOpen.Count == 0 ? 0 : 1)}");
        sb.AppendLine();

        Discrepancies(sb, quests, rewards, allowlist, current);
        Section(sb, "## catalogWrong (quest facts)", quests.Where(r => r.Verdict == Verdict.CatalogWrong), allowlist, current);
        Section(sb, "## unresolved (quest facts): human review", quests.Where(r => r.Verdict == Verdict.Unresolved), allowlist, current);
        RewardSection(sb, "## catalogWrong (unique rewards)", rewards.Where(r => r.Verdict == Verdict.CatalogWrong), allowlist, current);
        RewardSection(sb, "## unresolved (unique rewards)", rewards.Where(r => r.Verdict == Verdict.Unresolved), allowlist, current);
        Candidates(sb, quests);
        AllowlistSummary(sb, allowlist, current);

        sb.AppendLine("## sourceLagging and notListed (Lodestone)");
        sb.AppendLine();
        var lag = quests.Where(r => r.Source == SourceNames.Lodestone && r.Fact == Facts.Listed && r.Verdict is Verdict.SourceLagging or Verdict.NotListed).OrderBy(r => r.RowId).ToList();
        if (lag.Count == 0)
        {
            sb.AppendLine("None.");
        }
        else
        {
            sb.AppendLine("| Row | Name | Verdict | Reason |");
            sb.AppendLine("|---:|---|---|---|");
            foreach (var r in lag)
            {
                sb.AppendLine($"| {r.RowId} | {Md(r.Name)} | {Verdicts.Name(r.Verdict)} | {Md(r.Reason)} |");
            }
        }

        sb.AppendLine();
        sb.AppendLine("## SystemReward[1] coverage");
        sb.AppendLine();
        sb.AppendLine($"Quests whose `Quest.SystemReward[1]` is non-zero: {systemRewardCoverage.Count}; named in `curated/system_unlocks.json`: {systemRewardCoverage.Count(c => c.Covered)}.");
        sb.AppendLine();
        sb.AppendLine("| Row | Name | SystemReward[1] | In system_unlocks.json |");
        sb.AppendLine("|---:|---|---:|---|");
        foreach (var (rowId, name, sr, covered) in systemRewardCoverage.OrderBy(c => c.SystemReward).ThenBy(c => c.RowId))
        {
            sb.AppendLine($"| {rowId} | {Md(name)} | {sr} | {(covered ? "yes" : "no")} |");
        }

        sb.AppendLine();
        Csv.Atomic(path, sb.ToString());
    }

    /// <summary>Every confirmed catalogWrong, one line per (row, fact) with all source values, the evidence and where the fix lands (the allowlist entry's <c>fix</c>, else the row's fixedIn).</summary>
    private static void Discrepancies(StringBuilder sb, IReadOnlyList<QuestRow> quests, IReadOnlyList<RewardRow> rewards, Allowlist allowlist, Version? current)
    {
        sb.AppendLine("## Discrepancies to fix");
        sb.AppendLine();
        sb.AppendLine("Rows where two independent sources agree against the catalog (quest facts) or the source shows a non-quest way to obtain a reward the catalog calls quest-only. Each names where the fix lands; the allowlist excuses the row until that release.");
        sb.AppendLine();
        var questGroups = quests.Where(r => r.Verdict == Verdict.CatalogWrong).GroupBy(r => (r.RowId, r.Fact)).OrderBy(g => g.Key.RowId).ThenBy(g => g.Key.Fact, StringComparer.Ordinal).ToList();
        sb.AppendLine($"### Quest facts ({questGroups.Count})");
        sb.AppendLine();
        if (questGroups.Count == 0)
        {
            sb.AppendLine("None.");
        }
        else
        {
            sb.AppendLine("| Row | Name | Fact | Catalog | Sources | Evidence | Fix | Allowlisted |");
            sb.AppendLine("|---:|---|---|---|---|---|---|---|");
            foreach (var g in questGroups)
            {
                var first = g.First();
                var allow = g.Select(r => allowlist.Covering(r, current)).FirstOrDefault(a => a is not null);
                var sources = string.Join("; ", g.Select(r => $"{r.Source}: {(r.SourceValue.Length > 0 ? r.SourceValue : "(absent)")}"));
                var evidence = string.Join(" ", g.Select(r => Link(r.SourceRef)).Distinct());
                var fix = allow?.Fix ?? (first.FixedIn.Length > 0 ? first.FixedIn : "(unassigned)");
                sb.AppendLine($"| {first.RowId} | {Md(first.Name)} | {first.Fact} | {Md(first.CatalogValue.Length > 0 ? first.CatalogValue : "(absent)")} | {Md(sources)} | {evidence} | {Md(fix)} | {(allow is null ? "no" : Allowlist.Label(allow))} |");
            }
        }

        sb.AppendLine();
        var rewardGroups = rewards.Where(r => r.Verdict == Verdict.CatalogWrong).GroupBy(r => (r.QuestRowId, r.Kind, r.RewardId, r.ItemId)).OrderBy(g => g.Key.QuestRowId).ThenBy(g => g.Key.Kind, StringComparer.Ordinal).ThenBy(g => g.Key.RewardId).ToList();
        sb.AppendLine($"### Unique rewards ({rewardGroups.Count})");
        sb.AppendLine();
        if (rewardGroups.Count == 0)
        {
            sb.AppendLine("None.");
        }
        else
        {
            sb.AppendLine("| Quest | Name | Kind | Reward | Claim | Sources | Evidence | Fix | Allowlisted |");
            sb.AppendLine("|---:|---|---|---|---|---|---|---|---|");
            foreach (var g in rewardGroups)
            {
                var first = g.First();
                var allow = g.Select(r => allowlist.Covering(r, current)).FirstOrDefault(a => a is not null);
                var sources = string.Join("; ", g.Select(r => $"{r.Source}: {r.SourceValue}"));
                var evidence = string.Join(" ", g.Select(r => Link(r.SourceRef)).Distinct());
                var fix = allow?.Fix ?? (first.FixedIn.Length > 0 ? first.FixedIn : "(unassigned)");
                sb.AppendLine($"| {first.QuestRowId} | {Md(first.QuestName)} | {first.Kind} | {first.RewardId}{(first.ItemId != 0 ? "/item " + first.ItemId : string.Empty)} {Md(first.RewardName)} | {Md(first.CatalogClaim)} | {Md(sources)} | {evidence} | {Md(fix)} | {(allow is null ? "no" : Allowlist.Label(allow))} |");
            }
        }

        sb.AppendLine();
    }

    /// <summary>Duty unlocks the wiki names for quests the sheet links to no duty: script-driven unlocks, the input list for curated/duty_unlocks.json.</summary>
    private static void Candidates(StringBuilder sb, IReadOnlyList<QuestRow> quests)
    {
        var rows = quests.Where(r => r.Fact == Facts.DutyUnlock && r.Verdict == Verdict.NotModeled && r.Reason.Contains("candidate", StringComparison.Ordinal)).OrderBy(r => r.RowId).ThenBy(r => r.Source, StringComparer.Ordinal).ToList();
        sb.AppendLine("## Duty unlocks the catalog does not model (candidates for curated/duty_unlocks.json)");
        sb.AppendLine();
        sb.AppendLine($"{rows.Count} rows. The sheet's InstanceContentUnlock and the ContentFinderCondition unlock criteria cover a minority of duty unlocks; the rest are script-driven and reach unique_quests.json only through curated/duty_unlocks.json. These are the wiki's (and, where fetched, Garland's) names for quests that file has no entry for, or an incomplete one. Not a gate failure: absence is not a claim. Review before promoting; ContentFinderCondition row ids are looked up as the curated README describes.");
        sb.AppendLine();
        if (rows.Count == 0)
        {
            sb.AppendLine("None.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Row | Name | Catalog | Source | Source duties | Evidence |");
        sb.AppendLine("|---:|---|---|---|---|---|");
        foreach (var r in rows)
        {
            sb.AppendLine($"| {r.RowId} | {Md(r.Name)} | {Md(r.CatalogValue.Length > 0 ? r.CatalogValue : "(none)")} | {r.Source} | {Md(r.SourceValue)} | {Link(r.SourceRef)} |");
        }

        sb.AppendLine();
    }

    private static void AllowlistSummary(StringBuilder sb, Allowlist allowlist, Version? current)
    {
        sb.AppendLine("## Allowlist");
        sb.AppendLine();
        sb.AppendLine($"{allowlist.Entries.Count} entries in `verification-allowlist.json`; each expires when the plugin version reaches `until`, after which `summary` fails until the row is re-verified or the entry renewed; a `settled` entry records a decision on the evidence, never expires and excuses its row only while the row reads a verdict it was settled on.");
        sb.AppendLine();
        if (allowlist.Entries.Count == 0)
        {
            sb.AppendLine("None.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Row | Fact | Source | Verdict | Until | Fix | Reason |");
        sb.AppendLine("|---:|---|---|---|---|---|---|");
        foreach (var e in allowlist.Entries.OrderBy(e => e.RowId == "*" ? 0 : uint.TryParse(e.RowId, out var id) ? id : 0).ThenBy(e => e.Fact, StringComparer.Ordinal).ThenBy(e => e.Source, StringComparer.Ordinal))
        {
            sb.AppendLine($"| {e.RowId} | {e.Fact} | {e.Source ?? "*"} | {(e.Verdict == Allowlist.Settled ? Allowlist.Label(e) : e.Verdict)} | {(e.Verdict == Allowlist.Settled ? "never" : e.Until)}{(Allowlist.Expired(e, current) ? " (expired)" : string.Empty)} | {Md(e.Fix ?? string.Empty)} | {Md(e.Reason)} |");
        }

        sb.AppendLine();
    }

    private static void Totals(StringBuilder sb, List<(string Source, Verdict Verdict)> rows)
    {
        var verdictOrder = Enum.GetValues<Verdict>();
        var sources = rows.Select(r => r.Source).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();
        sb.AppendLine("| Source | rows | " + string.Join(" | ", verdictOrder.Select(Verdicts.Name)) + " |");
        sb.AppendLine("|---|---:|" + string.Concat(verdictOrder.Select(_ => "---:|")));
        foreach (var source in sources)
        {
            var of = rows.Where(r => r.Source == source).ToList();
            sb.AppendLine($"| {source} | {of.Count} | " + string.Join(" | ", verdictOrder.Select(v => of.Count(r => r.Verdict == v))) + " |");
        }

        sb.AppendLine($"| **all** | {rows.Count} | " + string.Join(" | ", verdictOrder.Select(v => rows.Count(r => r.Verdict == v))) + " |");
        sb.AppendLine();
    }

    private static void Section(StringBuilder sb, string heading, IEnumerable<QuestRow> rows, Allowlist allowlist, Version? current)
    {
        var list = rows.OrderBy(r => r.RowId).ThenBy(r => r.Fact, StringComparer.Ordinal).ThenBy(r => r.Source, StringComparer.Ordinal).ToList();
        sb.AppendLine(heading);
        sb.AppendLine();
        if (list.Count == 0)
        {
            sb.AppendLine("None.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Row | Name | Fact | Catalog | Source | Source value | Reason | Fixed in | Allowlisted | Allowlist reason | Evidence |");
        sb.AppendLine("|---:|---|---|---|---|---|---|---|---|---|---|");
        foreach (var r in list)
        {
            var allow = allowlist.Covering(r, current);
            sb.AppendLine($"| {r.RowId} | {Md(r.Name)} | {r.Fact} | {Md(r.CatalogValue)} | {r.Source} | {Md(r.SourceValue)} | {Md(r.Reason)} | {Md(r.FixedIn)} | {(allow is null ? "no" : Allowlist.Label(allow))} | {Md(allow?.Reason ?? string.Empty)} | {Link(r.SourceRef)} |");
        }

        sb.AppendLine();
    }

    private static void RewardSection(StringBuilder sb, string heading, IEnumerable<RewardRow> rows, Allowlist allowlist, Version? current)
    {
        var list = rows.OrderBy(r => r.QuestRowId).ThenBy(r => r.Kind, StringComparer.Ordinal).ThenBy(r => r.RewardId).ToList();
        sb.AppendLine(heading);
        sb.AppendLine();
        if (list.Count == 0)
        {
            sb.AppendLine("None.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Quest | Name | Kind | Reward | Claim | Source | Source value | Reason | Fixed in | Allowlisted | Evidence |");
        sb.AppendLine("|---:|---|---|---|---|---|---|---|---|---|---|");
        foreach (var r in list)
        {
            var allow = allowlist.Covering(r, current);
            sb.AppendLine($"| {r.QuestRowId} | {Md(r.QuestName)} | {r.Kind} | {r.RewardId}{(r.ItemId != 0 ? "/item " + r.ItemId : string.Empty)} {Md(r.RewardName)} | {Md(r.CatalogClaim)} | {r.Source} | {Md(r.SourceValue)} | {Md(r.Reason)} | {Md(r.FixedIn)} | {(allow is null ? "no" : Allowlist.Label(allow))} | {Link(r.SourceRef)} |");
        }

        sb.AppendLine();
    }

    private static string Md(string s) => s.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");

    private static string Link(string url) => url.StartsWith("http", StringComparison.Ordinal) ? $"[link]({url})" : Md(url);
}
